#!/usr/bin/env bash
# SHIELD Framework - Run All Security Checks
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/lib/cli.sh"

echo "================================================"
echo "  SHIELD Security Assessment Framework"
echo "================================================"
echo ""
echo "Target(s): ${ARGS[*]}"
echo "Output directory: $OUT"

if [[ "${BRUTE_FORCE:-false}" == "true" ]]; then
    echo ""
    echo "⚠⚠⚠  BRUTE FORCE MODE ACTIVE  ⚠⚠⚠"
    echo "  Only use against sites you own or have written authorisation for."
    echo "  Max 10 attempts per target. Stops on first lockout."
    echo ""
fi
echo ""

# Clean and recreate output directory structure (ensures no stale results from previous scans)
rm -rf "$OUT"/{step1,step2,step3,step4,step5,step6}
mkdir -p "$OUT"/{step1,step2,step3,step4,step5,step6}

# Run all step scripts
STEPS=(
    "step1/scope.sh"
    "step1/wp_version.sh"
    "step1/authenticate.sh"
    "step2/headers.sh"
    "step2/http_redirect.sh"
    "step2/hsts_advanced.sh"
    "step2/https.sh"
    "step2/tls.sh"
    "step2/tls_protocols.sh"
    "step2/tls_ciphers.sh"
    "step2/csp_quality.sh"
    "step2/server_leakage.sh"
    "step2/cert_expiry.sh"
    "step2/advanced_headers.sh"
    "step2/cache_control.sh"
    "step2/exposure.sh"
    "step2/ocsp_stapling.sh"
    "step2/server_version.sh"
    "step2/php_version.sh"
    "step3/cookie_flags.sh"
    "step3/discover.sh"
    "step3/logout.sh"
    "step3/ratelimit.sh"
    "step3/session_rotation.sh"
    "step3/timeout.sh"
    "step3/user_enumeration.sh"
    "step3/session_fixation.sh"
    "step3/login_protection.sh"
    "step3/brute_force_check.sh"
    "step3/wp_users.sh"
    "step4/access_control.sh"
    "step4/sensitive_files.sh"
    "step4/admin_paths.sh"
    "step4/cors_check.sh"
    "step4/directory_listing.sh"
    "step4/api_auth.sh"
    "step4/graphql.sh"
    "step4/cloud_storage.sh"
    "step4/file_upload.sh"
    "step4/backup_files.sh"
    "step4/path_traversal.sh"
    "step4/http_methods.sh"
    "step4/wp_plugins.sh"
    "step4/xmlrpc.sh"
    "step4/wp_debug.sh"
    "step4/wp_config_exposure.sh"
    "step4/installed_plugins_auth.sh"
    "step4/dangerous_plugins_auth.sh"
    "step4/file_editors_auth.sh"
    "step5/owasp_defensive.sh"
    "step5/verbose_errors.sh"
    "step5/open_redirect.sh"
    "step5/sri_check.sh"
    "step5/third_party_scripts.sh"
    "step5/php_info.sh"
    "step5/error_pages.sh"
    "step5/malicious_content.sh"
    "step5/cloaking_check.sh"
    "step5/webshell_paths.sh"
    "step5/env_exposure.sh"
    "step5/threat_intel.sh"
    "step6/infra_exposure.sh"
    "step6/dns_hygiene.sh"
    "step6/subdomain_enum.sh"
    "step6/waf_fingerprint.sh"
    "step6/shared_hosting.sh"
    "step6/port_scan.sh"
    "step6/dns_integrity.sh"
    "step6/cert_transparency.sh"
)

for script in "${STEPS[@]}"; do
    script_path="$SCRIPT_DIR/$script"
    if [[ -f "$script_path" ]]; then
        echo "▶ Running $(basename "$script" .sh)..."
        bash "$script_path" "${ARGS[@]}" -o "$OUT" || echo "  ⚠ Warning: $script had errors"
        echo ""
    fi
done

echo "================================================"
echo "  Assessment Complete"
echo "================================================"
echo "Results saved to: $OUT"
echo ""
echo "Generating consolidated report..."
"$SCRIPT_DIR/generate_report.sh" -i "$OUT" -o "$OUT/report.md"
echo ""
echo "✓ Full report available at: $OUT/report.md"
echo ""
